---
- name: "Fix 'configured multiple times'"
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/repo_yandex_ru_yandex_disk_deb.list"
    state: absent

- name: "Refresh apt sources list"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: "Ensure dependencies are installed"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "gpgv"
      - "gnupg"
      - "apt-transport-https"

- name: "Add GPG key"
  ansible.builtin.apt_key:
    url: "{{ yadisk_cli_gpg_key_url }}"

- name: "Add repository"
  ansible.builtin.apt_repository:
    repo: "{{ yadisk_cli_deb_source }}"
    filename: "yandex-disk"
    state: present

- name: "Install Yandex Disk"
  ansible.builtin.apt:
    name: "{{ yadisk_cli_package }}"
    state: present
